# Generated by Django 3.1.5 on 2021-01-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='kakeibo',
            options={'verbose_name': '家計簿', 'verbose_name_plural': '家計簿'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('in', '収入'), ('out', '支出')], default='in', max_length=3, verbose_name='収支'),
            preserve_default=False,
        ),
    ]
